name: Contracts Tests
on:
  push:
    paths:
      - 'packages/contracts/**'
      - '.github/workflows/contract-*.yml'

env:
  working-directory: packages/contracts

jobs:
  test-hardhat:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn
        run: npm i -G yarn
      - name: Install dependencies
        run: yarn
      - name: Compile contracts
        run: yarn run compile
      - name: Run Hardhat Tests
        env:
          REPORT_GAS: true
        run: yarn run test

  test-slither-echidna:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn
        run: npm i -G yarn
      - name: Install dependencies
        run: yarn
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: 'x64'

      - name: Install slither
        run: |
          pip3 install slither-analyzer
          echo "check installed slither version....."
          pip3 show slither-analyzer

      - name: Install solc
        env:
          SOLC_VERSION: 0.8.4
        run: |
          pip install solc-select
          solc-select install ${{ env.SOLC_VERSION }}
          solc-select use ${{ env.SOLC_VERSION }}

      - name: Install echidna
        run: |
          sudo wget -O /tmp/echidna-test.tar.gz https://github.com/crytic/echidna/releases/download/v1.5.1/echidna-test-v1.5.1-Ubuntu-18.04.tar.gz
          sudo tar -xf /tmp/echidna-test.tar.gz -C /usr/bin
          sudo chmod +x /usr/bin/echidna-test

      - name: Run Slither Static Analyzer
        run: slither .

      - name: Run echina tests
        run: |
          echidna-test . --contract RegistryEchidnaTest  --config echidna.config.yml