name: Storybook Deploy
on:
  push:
    paths:
      - 'packages/ui-components/**'
    branches:
      - 'main'

env:
  working-directory: packages/ui-components

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn deploy-storybook --ci --host-token-env-variable=GITHUB_TOKEN
