name: UI-Components release
on:
  pull_request:
    types:
      - closed

jobs:
  test:
    uses: ./.github/workflows/ui-components-test.yml
  prepare:
    runs-on: ubuntu-latest
    name: Prepare release
    if: github.event.pull_request.merged
    outputs:
      bump: ${{ steps.patch.outputs.bump }}${{ steps.minor.outputs.bump }}${{ steps.major.outputs.bump }}
    steps:
      - name: Is patch
        id: patch
        if: contains( github.event.pull_request.labels.*.name, 'ui-components:patch')
        run: echo "bump=patch" >> $GITHUB_OUTPUT
      - name: Is minor
        id: minor
        if: contains( github.event.pull_request.labels.*.name, 'ui-components:minor')
        run: echo "bump=minor" >> $GITHUB_OUTPUT
      - name: Is major
        id: major
        if: contains( github.event.pull_request.labels.*.name, 'ui-components:major')
        run: echo "bump=major" >> $GITHUB_OUTPUT
  createTag:
    runs-on: ubuntu-latest
    name: Create tag
    needs: [test, prepare]
    if: ${{ needs.prepare.outputs.bump != '' }}
    defaults:
      run:
        working-directory: packages/ui-components
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ARABOT_PAT }}
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: bump version
        id: bump
        run: |
          yarn version --${{ needs.prepare.outputs.bump }} --no-git-tag-version
          VERSION=$(cat package.json | jq -r .version)      
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Commit new package version
        id: commit
        run: |
          cd ../../
          git fetch
          git pull
          git config --global user.name "Arabot-1"
          git config --global user.email "arabot-1@users.noreply.github.com"
          git add ./packages/ui-components/package.json
          git commit -am "Updates version in package.json for ui-components"
          git push
          echo "commitid=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: create tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ARABOT_PAT }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ steps.bump.outputs.version }}-ui-components`,
              sha: "${{ steps.commit.outputs.commitid }}"
            })